name: Build and Deploy Docker
on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@master

    - name: Build Container
      run: docker build . -t ghcr.io/${{ github.repository }}:${{ github.sha }} -t ghcr.io/${{ github.repository }}:latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1.14.1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.ACTIONS_PAT }}

    - name: Push Container
      run: docker push ghcr.io/${{ github.repository }}:latest